import { getStorage, ref, uploadBytes } from "firebase/storage";
import { FIREBASE_OBJECTS } from "./firebase";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { useAuth } from "./contexts/AuthContext";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
export function pushFile(file, doc) {
  let uploaded = false;
  var storageRef = ref(FIREBASE_OBJECTS.storage, doc);

  // 'file' comes from the Blob or File API
  uploadBytes(storageRef, file).then((snapshot) => {
    alert("Uploaded an art piece request successfully!");
  });
  return uploaded;
}

export function make_id(length) {
  var result = "";
  var characters =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  var charactersLength = characters.length;
  for (var i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
}

export function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
